config/routes.rb
Rails.application.routes.draw do
  resources :questions do
  	resources :answers
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#homepage'
  get 'tags/:tag', to: 'questions#index', as: :tag
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  def self.search(search)
  	where("body LIKE ?", "%#{search}%")
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	has_many :answers
	validates_presence_of :date, :text
	acts_as_taggable 

	def self.search(search)
  	where("text LIKE ?", "%#{search}%")
	end
end

app/models/user.rb
class User < ApplicationRecord
	has_many :questions
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end
 
  private
    def answer_params
      params.require(:answer).permit(:user, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :set_question, only: [:show, :edit, :update]
	before_action :question_owner, only: [:edit, :update, :destroy]
	
	def index
		@questions = Question.all
  		if params[:search]
				@questions = Question.search(params[:search]) + Answer.search(params[:search])
		  elsif params[:tag]
  			@questions = Question.tagged_with(params[:tag])
			else  			
		    @questions = Question.all.order('created_at DESC')
		end
	end

	def new
		@question = Question.new
	end

	def edit
	end

	def create
		@question = Question.new(question_params)
		@question.user_id = current_user.id

		if @question.save
			redirect_to @question, notice: 'Your question was created successfully'
		else
			render :new
		end
	end

	def show
		
	
	end

	def update
	  if @question.update(question_params)
	    redirect_to @question
	  else
	    render 'edit'
  end
end


	private
	def question_params
		params.require(:question).permit(:date, :text, :tag_list)
	end

	def set_question
		@question = Question.find(params[:id])
	end

  def question_owner
	 unless @question.user_id == current_user.id
	  flash[:notice] = 'Access denied'
	  redirect_to questions_path
   end
 end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
	def homepage
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active?(path)
		"active" if current_page?(path)
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
  <p>
    <strong>Submitter:</strong>
    <%= answer.user %>
  </p>
 
  <p>
    <strong>Answer:</strong>
    <%= answer.body %>
  </p>
  <hr>

app/views/answers/_form.html.erb
<%= form_for([@question, @question.answers.build]) do |f| %>
  <%= f.label :Submitter %><br>
  <%= f.text_field :user %><br>
  <br>
  <%= f.label :body %><br>
  <%= f.text_area :body %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
 
    <div class="row">
      <div class="col-md-12">
        <%= render 'shared/nav' %>
        <%= yield %>
        </div>
      </div>
  </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div>
<br>
<%= form_for @question, class: "form-horizontal" do |f| %>
	 <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


	<div class="form-group">
		<%= f.label :date, class: "col-sm-2 control-label" %>
		<%= f.date_field :date, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :text, class: "col-sm-2 control-label" %>
		<%= f.text_area :text, class: "form-control" %>
	</div>

  <div class='field'>
    <%= f.label :tag_list, 'Tags (separated by commas)' %><br/>
    <%= f.text_field :tag_list %>
  </div>

	<%= f.submit 'Save', class: 'btn btn-primary btn-block' %>
<% end %>
</div>

app/views/questions/_question.html.erb
	<tr>
		<td>
			<%= question.id %>
		</td>

		<td>
			<%= question.date %>
		</td>
		<td>
			<%= question.user.email %>
		</td>
		<td>
			<%= link_to truncate(question.text), question %>
		</td>
		<td>
			Tags: <%= raw(question.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %>
		</td>
		<td>
			<% if question.user_id == current_user.id %>
				<%= link_to 'Edit', edit_question_path(question), class: "btn btn-success btn-sm" %>
			<% else %>
				<%= link_to 'Edit', edit_question_path(question), class: "btn btn-primary btn-sm disabled" %>
			<% end %>



	</tr>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div>
	<div class="btn pull-right">
		<%= form_tag(questions_path, :method => "get", id: "search-form") do %>
		<strong>Search Questions or Answers:</strong>
		<%= text_field_tag :search, params[:search], placeholder: "Search Q/A" %>
		<%= submit_tag "Search" %>
		<% end %>
	</div>
	<h3>Questions</h3>
	<table class="table table-hover table-striped">
			<thead>
				<tr>
					<th>
						#
					</th>
					<th>
						Date
					</th>
					<th>
						User
					</th>
					<th>
						Question
					</th>
					<th>
						Tags
					</th>
				
				</tr>
			</thead>

			<tbody>
				<%= render @questions %>
		</tbody>
	</table>
</div>

app/views/questions/new.html.erb
<%= form_for @question do |f| %>

  <%= f.date_field :date %>
  <%= f.text_area :text %>
  
	<%= f.submit "Save" %>

<% end %>

app/views/questions/show.html.erb
<p>
  <strong>Date</strong>
  <%= @question.date %>
</p>
 
<p>
  <strong>Question</strong>
  <%= @question.text %>
</p>
 
 <h3>Answers</h3>
  <%= render @question.answers %>

 <h3>Add an answer</h3>
  <%= render 'answers/form' %>

<%= link_to 'Back', questions_path %>

app/views/shared/_nav.html.erb
<div class="logo">
	<h1>Stack App</h1>	
</div>
<ul class="custom-nav nav nav-tabs">
	<li class="<%= active?(root_path) %>">
		<%= link_to "Home", root_path%>
	</li>

	<li class="<%= active?(questions_path) %>">
		<%= link_to "Questions", questions_path%>
	</li>

	<li class="<%= active?(new_question_path) %>">
		<%= link_to "Post Question", new_question_path%>
	</li>


	<li class="dropdown pull-right">
		 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Account<strong class="caret"></strong></a>
		<ul class="dropdown-menu">
			<li>
				<%= link_to "Edit Details", edit_user_registration_path %>
			</li>
			<li class="divider">
			</li>
			<li>
				<%= link_to "Logout", destroy_user_session_path, method: :delete %>
			</li>
		</ul>
	</li>
	</ul>